### PR TITLE
Feature/animated icon

### PR DESCRIPTION
**Pull request by tekkies**

### CODE REVIEW

**Comment by tekkies** [comment]
Oops - I thought I was in my repo

**Comment by rambotech** [comment]
No worries.  I will pull it from yours to see the changes.  I like what I see.

**Comment by tekkies** [comment]
Thanks John.

I am getting some GDI errors on the bitmap after it's been running a while
- I'm still looking into that.

Thanks for creating the sample app.  It really helped me get started.

Andy

**Comment by tekkies** [comment]
I think I fixed it now on the master branch

**Comment by rambotech** [comment]
The behavior still looks right.  That time between Form.Close() and the app actually terminating is fun. Welcome to state programming.

**Pull request closed without merging**
